version: '3'
services:
  app:
    build:
      context: .
      dockerfile: 1.Dockerfile
    tty: true
    ports:
      - 8000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
